# Generated by Django 5.2.3 on 2025-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_upvote',
            field=models.BooleanField(default=True),
        ),
    ]
